### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by platomav** [IllegalArgument/Huffman11#1]
Hello,

Amazing work so far. Since I have no other means of contact, I opened an issue here. Can you create an account over at [Win-Raid ](http://www.win-raid.com/forum.php) forum?

![](https://user-images.githubusercontent.com/11527726/27930496-77804ad2-629f-11e7-84d1-edfac573ddc4.PNG)

**Comment by IllegalArgument** [comment]
Thanks! I'm now IllegalArgument at the Win-Raid forum as well, so feel free to contact me there too. Looking at the screenshot, I'm guessing there was an unknown codeword in that kernel module. The decompression script should print out something like `Unknown codeword ... (...) at decompressed offset 0x...` when it encounters a codeword that it doesn't know the corresponding symbol for. I'd be happy to take a look at that module if you don't mind uploading it.
